"""empty message

Revision ID: 075c3964d491
Revises: e872623c3a6b
Create Date: 2025-05-14 09:58:16.869064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075c3964d491'
down_revision = 'e872623c3a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
