"""Add rating, is_read, and abstract to Book

Revision ID: 96999f433212
Revises: 
Create Date: 2025-04-25 00:34:25.312742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96999f433212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('abstract', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('abstract')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
