"""Add is_read, rating, and abstract to Book

Revision ID: e872623c3a6b
Revises: 96999f433212
Create Date: 2025-04-25 01:03:43.147912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e872623c3a6b'
down_revision = '96999f433212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
